version: '3'

services: 
    myredis:
        image: 'redis:alpine'
    mypostgres:
        image: 'postgres:alpine'
        environment: 
            - POSTGRES_PASSWORD=12345678A!
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        volumes: 
            - C:/Users/pc/Desktop/Studia/Devops/devops/postgres:/var/lib/postgresql/data
    mybackend:
        image: 'xallal/mybackend_dev'
        build:
            dockerfile: Dockerfile.dev
            context: ./mybackend
        volumes: 
            - /opt/app/node_modules/
            - /C:/Users/pc/Desktop/Studia/Devops/devops/mybackend:/opt/app
        ports: 
            - "4000:4000"
        environment: 
            - POSTGRES_PASSWORD=12345678A!
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - REDIS_HOST=myredis
            - POSTGRES_HOST=mypostgres